# Generated by Django 5.0.6 on 2024-05-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='menu_items',
            field=models.ManyToManyField(through='restaurant.OrderItem', to='restaurant.menuitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='state_province',
            field=models.CharField(choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('WA', 'Western Australia'), ('TAS', 'Tasmania'), ('NT', 'Northern Territory'), ('ACT', 'Australian Capital Territory')], default='VIC', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_postal_code',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='Received', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
