# Generated by Django 5.0.6 on 2024-05-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='menu_items',
            new_name='order_items',
        ),
    ]
