# Generated by Django 5.0.6 on 2024-05-22 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_menu_items_order_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.order'),
        ),
    ]
